-- Create Trains Table
CREATE TABLE Trains (
    train_id INT AUTO_INCREMENT PRIMARY KEY,
    train_name VARCHAR(255) NOT NULL,
    station VARCHAR(255) NOT NULL
);

-- Populate Trains Table
INSERT INTO Trains (train_name, station) VALUES
('London Express', 'London Euston'),
('Northern Line', 'Manchester Piccadilly'),
('Glasgow Service', 'Glasgow Central'),
('Edinburgh Express', 'Edinburgh Waverley'),
('Reading to York', 'Reading'),
('Newcastle to Sheffield', 'Newcastle'),
('Nottingham to Cardiff', 'Nottingham'),
('Southampton to Brighton', 'Southampton Central'),
('Norwich to Exeter', 'Norwich'),
('Cambridge Line', 'Cambridge'),
('London Express', 'London Euston'),
('Northern Line', 'Manchester Piccadilly'),
('Glasgow Service', 'Glasgow Central'),
('Edinburgh Express', 'Edinburgh Waverley'),
('Reading to York', 'Reading'),
('Newcastle to Sheffield', 'Newcastle'),
('Nottingham to Cardiff', 'Nottingham'),
('Southampton to Brighton', 'Southampton Central'),
('Norwich to Exeter', 'Norwich'),
('Cambridge Line', 'Cambridge'),
('London Express', 'London Euston'),
('Northern Line', 'Manchester Piccadilly'),
('Glasgow Service', 'Glasgow Central'),
('Edinburgh Express', 'Edinburgh Waverley'),
('Reading to York', 'Reading'),
('Newcastle to Sheffield', 'Newcastle'),
('Nottingham to Cardiff', 'Nottingham'),
('Southampton to Brighton', 'Southampton Central'),
('Norwich to Exeter', 'Norwich'),
('Cambridge Line', 'Cambridge'),
('London Express', 'London Euston'),
('Northern Line', 'Manchester Piccadilly'),
('Glasgow Service', 'Glasgow Central'),
('Edinburgh Express', 'Edinburgh Waverley'),
('Reading to York', 'Reading'),
('Newcastle to Sheffield', 'Newcastle'),
('Nottingham to Cardiff', 'Nottingham'),
('Southampton to Brighton', 'Southampton Central'),
('Norwich to Exeter', 'Norwich'),
('Cambridge Line', 'Cambridge');
